# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "1220a5d115dc84e46b95b2ba6b3f016c4d88acd44ecb63195f9d3eec4dfcd4b3d5b8";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/6aa5180eeadde1475359dea355ce3df534e4ab4b.tar.gz";
      hash = "sha256-+9AwxF3BbkHB1lvtEkD93XQd/cBf7pM3Nzhz37sp/LM=";
    };
  }
]
