# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12209e829da9d7d0bc089e4e0cbc07bb882f6192cd583277277da34df53cd05b8f2a";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/9c23bcb5aebe0c2542b4de4472f60959974e2222.tar.gz";
      hash = "sha256-JgwFF/T3tq1Ox8pLjhMIgf71nxK8riyLxre9RlcJCKE=";
    };
  }
]
